language: python
python:
    - "2.7"

sudo: required

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - gcc-4.9
            - g++-4.9

# Cache PlatformIO packages using Travis CI container-based infrastructure
cache:
    directories:
        - "~/.platformio"

env:
    - PLATFORMIO_CI_SRC=examples/LEDTransition/LEDTransition.ino
    - PLATFORMIO_CI_SRC=examples/LEDTransition/LEDTransition.ino
    - PLATFORMIO_CI_SRC=examples/LEDTransition/LEDTransition.ino

before_install:
    # Setup Test Environment
    - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 90
    - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 90
    - sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-4.9 90

install:
    # Check GCC versions
    - g++ --version
    - gcc --version
    - gcov --version

    - pip install -U platformio
    - cd ../
    - git clone https://github.com/r89m/ArduinoFrameworkFake.git
    - cd $TRAVIS_BUILD_DIR
    # Login to PioPlus
    - pio account login --username $PIO_PLUS_USERNAME --password $PIO_PLUS_PASSWORD

before_script:
    # Run tests
    - platformio test -e native

script:
    # Check that the example builds
    - platformio ci --lib "." --board=uno --project-option="build_flags=-Werror" --verbose