language: python
python:
    - "2.7"

# Cache PlatformIO packages using Travis CI container-based infrastructure
sudo: false
cache:
    directories:
        - "~/.platformio"

env:
    - PLATFORMIO_CI_SRC=examples/LEDTransition/LEDTransition.ino
    - PLATFORMIO_CI_SRC=examples/LEDTransition/LEDTransition.ino
    - PLATFORMIO_CI_SRC=examples/LEDTransition/LEDTransition.ino

install:
    - pip install -U platformio
    - cd ../
    - git clone https://github.com/r89m/ArduinoFrameworkFake.git

before_script:
    # Run tests
    - platformio test -e native

script:
    # Check that the example builds
    - platformio ci --board=uno --project-option="build_flags=-Werror"